baseURL = "https://alfahrelrifananda.my.id/"
languageCode = "en-us"
title = "AlfahrelRifananda"
copyright = "Â© AlfahrelRifananda"
theme = "archie"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
	mode="toggle"
	useCDN=false
  customcss = ["css/custom.css"]
  favicon = "/favicon.png"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/alfahrelrifananda/"

[[menu.main]]
name = "Home"
url = "https://alfahrelrifananda.my.id/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
