baseURL = "https://alfahrelrifananda.my.id/"
languageCode = "en-us"
title = "AlfahrelRifananda"
copyright = "Â© AlfahrelRifananda"
theme = "archie"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
	mode="toggle"
	useCDN=false
	subtitle = "Minimal and Clean [blog theme for Hugo](https://github.com/athul/archie)"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/alfahrelrifananda/"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/alfahrelrifananda/"

[[params.social]]
name = "GitLab"
icon = "gitlab"
url = "https://gitlab.com/alfahrelrifananda/"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
